### ISSUE TITLE
practica sonar cloud

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-entrevista-gestion-de-proyectos#1]
[PRACTICA 5_SONAR CLOUD_GESTION DE PROYECTOS.pdf](https://github.com/SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-entrevista-gestion-de-proyectos/files/9669045/PRACTICA.5_SONAR.CLOUD_GESTION.DE.PROYECTOS.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
